base_url = "https://a-programming-odyssey.netlify.app"
title = "A Programming Odyssey"

theme = "zap"

compile_sass = false
default_language = "en"

# Use `rss.xml` for RSS feeds and `atom.xml` for ATOM.
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

taxonomies = [
    {name = "tags"},
    {name = "categories"}
]

[search]
index_format = "fuse_javascript"

[markdown]

[markdown.highlighting]
theme = "vesper"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
keywords = "blog, tech, privacy"
author = "oraqlle"

favicon = "/favicon.ico"
favicon_mimetype = "image/ico"

inline_icons = true
icon_path = "static/icons/"
icons = [
  "home",
  "chat",
  "color-palette",
  "idea",
  "search",
  "light",
  "asleep",
  "rss",
]

# Search page path
search_path = "$BASE_URL/search/"

image_resizing_disabled = false
image_format = "auto"
image_quality = 80
images_default_size = 1024
images_sizes = [512, 1024, 2048]

thumbnail_quality = 70
thumbnail_default_size = 256
thumbnail_sizes = [128, 256]

menu_links = [
    { name = "home", url = "$BASE_URL", icon = "home.svg" },
    { name = "blog", url = "$BASE_URL/posts/", icon = "chat.svg" },
    { name = "gallery", url = "$BASE_URL/gallery/", icon = "color-palette.svg" },
    { name = "tags", url = "$BASE_URL/tags/", icon = "idea.svg"},
    #{ name = "archive", url = "$BASE_URL/archive" },
    { name = "about me", url = "$BASE_URL/about" },
    { name = "codeberg", url = "https://codeberg.org/oraqlle", newtab = true },
    { name = "github", url = "https://github.com/oraqlle", newtab = true },
]

enable_post_view_navigation = true

post_view_navigation_prompt = "Thanks for reading! Read other posts?"
